- name: Build and Deploy to Cloud Run
      run: |
        # 1. บิลด์อิมเมจโดยใช้ Dockerfile (ที่มึงเพิ่งสร้าง)
        gcloud builds submit --tag asia-southeast1-docker.pkg.dev/followsubthai-3a814/followsubthai/webapp .
        
        # 2. ดีพพลอยขึ้น Cloud Run
        gcloud run deploy followsubthai \
          --image asia-southeast1-docker.pkg.dev/followsubthai-3a814/followsubthai/webapp \
          --platform managed \
          --region asia-southeast1 \
          --allow-unauthenticated \
          --port 3000
